spring:
  application:
    name: architecture

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        #show-sql: true
        format_sql: true


  datasource:
    url: jdbc:mariadb://localhost:3306/HHPLUS
    username: hhplus
    password: hhplus_dba
    driver-class-name: org.mariadb.jdbc.Driver  # MariaDB JDBC 드라이버 지정

logging:
  level:
    org.hibernate.SQL: debug